---
openapi: 3.0.0
info:
  title: Clientes V1
  description: "This application retrieve the basic client information"
  contact:
    name: Jorge A. Vázquez Mendoza
    email: jorge.vazquez@devsu.com
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development
tags:
  - name: Cliente
    description: Cliente controller
paths:
  /cliente:
    get:
      tags:
        - Cliente
      summary: Retrieve the basic client data
      description: Retrieve the basic client data using the client identification
      operationId: GetClient
      parameters:
        - name: personIdentification
          in: query
          description: |-
            <sup><i>(ES)</i></sup> Identificación de un cliente. Ejemplo: (CIF, Cédula, Pasaporte, RUC)
            <br><br>
            <sup><i>(EN)</i></sup> Identification of a client. Example: (CIF, ID, Passport, RUC)
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: "0000000000"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClientResponse'
        "400":
          description: 400 Bad Request. The request information it's not correct.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 401 Unauthorized.You're not authorized to perform this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: 403 Forbidden. You don't have the right permissions to execute this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 404 Not Found. The server cannot find the requested resource.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 Internal Server Error. An error has occurred.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "502":
          description: 502 Bad Gateway. The service unable to get a valid response.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Cliente
      summary: Save a new client in the DB
      description: Save a new cliente in the DB
      operationId: PostClient
      requestBody:
        description: Create a new client in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostClientRequest'
      responses:
        "200":
          description: Cliente creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostClientResponse'
        "400":
          description: 400 Bad Request. The request information it's not correct.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 401 Unauthorized.You're not authorized to perform this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: 403 Forbidden. You don't have the right permissions to execute this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 404 Not Found. The server cannot find the requested resource.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 Internal Server Error. An error has occurred.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "502":
          description: 502 Bad Gateway. The service unable to get a valid response.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Cliente
      summary: Update the client in the DB
      description: Update the cliente in the DB
      operationId: PutClient
      parameters:
        - name: personIdentification
          in: query
          description: |-
            <sup><i>(ES)</i></sup> Identificación de un cliente. Ejemplo: (CIF, Cédula, Pasaporte, RUC)
            <br><br>
            <sup><i>(EN)</i></sup> Identification of a client. Example: (CIF, ID, Passport, RUC)
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: "0000000000"
      requestBody:
        description: Update the client in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutClientRequest'
      responses:
        "200":
          description: Cliente actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutClientResponse'
        "400":
          description: 400 Bad Request. The request information it's not correct.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 401 Unauthorized.You're not authorized to perform this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: 403 Forbidden. You don't have the right permissions to execute this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 404 Not Found. The server cannot find the requested resource.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 Internal Server Error. An error has occurred.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "502":
          description: 502 Bad Gateway. The service unable to get a valid response.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Cliente
      summary: Delete a client
      description: Revome a client from the DB
      operationId: DeleteClient
      parameters:
        - name: personIdentification
          in: query
          description: |-
            <sup><i>(ES)</i></sup> Identificación de un cliente. Ejemplo: (CIF, Cédula, Pasaporte, RUC)
            <br><br>
            <sup><i>(EN)</i></sup> Identification of a client. Example: (CIF, ID, Passport, RUC)
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: "0000000000"
      responses:
        "200":
          description: Cliente eliminado exitosamente
        "400":
          description: 400 Bad Request. The request information it's not correct.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 401 Unauthorized.You're not authorized to perform this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: 403 Forbidden. You don't have the right permissions to execute this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 404 Not Found. The server cannot find the requested resource.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 Internal Server Error. An error has occurred.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "502":
          description: 502 Bad Gateway. The service unable to get a valid response.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetClientResponse:
      type: object
      properties:
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
    PostClientRequest:
      type: object
      properties:
        identification:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Identificacion de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Person Id.
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        gender:
          maxLength: 10
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Genero de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Gender of a person.
        birthDate:
          type: string
          format: date
          description: |-
            <sup><i>(ES)</i></sup> Fecha de nacimiento de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Date of birth of a person.
        password:
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Contrasena de una persona
            <br><br>
            <sup><i>(EN)</i></sup> User password
    PostClientResponse:
      type: object
      properties:
        clientId:
          type: number
          description: |-
            <sup><i>(ES)</i></sup> Identificador unico del cliente
            <br><br>
            <sup><i>(EN)</i></sup> Cliente unique Id
        identification:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Identificacion de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Person Id.
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        gender:
          maxLength: 10
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Genero de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Gender of a person.
        birthDate:
          type: string
          format: date
          description: |-
            <sup><i>(ES)</i></sup> Fecha de nacimiento de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Date of birth of a person.
    PutClientRequest:
      type: object
      properties:
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        gender:
          maxLength: 10
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Genero de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Gender of a person.
        birthDate:
          type: string
          format: date
          description: |-
            <sup><i>(ES)</i></sup> Fecha de nacimiento de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Date of birth of a person.
        password:
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Contrasena de una persona
            <br><br>
            <sup><i>(EN)</i></sup> User password
    PutClientResponse:
      type: object
      properties:
        clientId:
          type: number
          description: |-
            <sup><i>(ES)</i></sup> Identificador unico del cliente
            <br><br>
            <sup><i>(EN)</i></sup> Cliente unique Id
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        gender:
          maxLength: 10
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Genero de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Gender of a person.
        birthDate:
          type: string
          format: date
          description: |-
            <sup><i>(ES)</i></sup> Fecha de nacimiento de una persona.
            <br><br>
            <sup><i>(EN)</i></sup> Date of birth of a person.
    Error:
      required:
        - developerMessage
        - errorCode
        - userMessage
      type: object
      properties:
        errorCode:
          maxLength: 6
          pattern: "^[a-zA-Z]+$\\d+$"
          type: string
          example: "6"
        developerMessage:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: Coding Error
        userMessage:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: Error al validar dispositvo
        moreInfo:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: ""
        version:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: 1.0.0
        status:
          maxLength: 15
          type: number
          example: 409
  responses:
    BadRequest:
      description: 400 Bad Request. The request information it's not correct.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: 401 Unauthorized.You're not authorized to perform this operation.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: 403 Forbidden. You don't have the right permissions to execute this operation.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 404 Not Found. The server cannot find the requested resource.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: 500 Internal Server Error. An error has occurred.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    GatewayError:
      description: 502 Bad Gateway. The service unable to get a valid response.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'