---
openapi: 3.0.0
info:
  title: Clientes V1
  description: "This application retrieve the basic client information"
  contact:
    name: Jorge A. Vázquez Mendoza
    email: jorge.vazquez@devsu.com
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development
tags:
  - name: Cliente
    description: Cliente controller
paths:
  /cliente:
    get:
      tags:
        - Cliente
      summary: Retrieve the basic client data
      description: Retrieve the basic client data using the client identification
      operationId: GetClient
      parameters:
        - name: personIdentification
          in: query
          description: |-
            <sup><i>(ES)</i></sup> Identificación de un cliente. Ejemplo: (CIF, Cédula, Pasaporte, RUC)
            <br><br>
            <sup><i>(EN)</i></sup> Identification of a client. Example: (CIF, ID, Passport, RUC)
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: "0000000000"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClientResponse'
        "400":
          description: 400 Bad Request. The request information it's not correct.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 401 Unauthorized.You're not authorized to perform this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: 403 Forbidden. You don't have the right permissions to execute this operation.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 404 Not Found. The server cannot find the requested resource.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 Internal Server Error. An error has occurred.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        "502":
          description: 502 Bad Gateway. The service unable to get a valid response.
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetClientResponse:
      type: object
      properties:
        names:
          maxLength: 100
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Nombres de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Names of a person or client.
          format: ISODateTime-ISO8601 YYYY-MM-DD
        address:
          maxLength: 50
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Dirección de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
        phone:
          maxLength: 15
          type: string
          description: |-
            <sup><i>(ES)</i></sup> Telefono de una persona o cliente.
            <br><br>
            <sup><i>(EN)</i></sup> Address of a person or client.
    Error:
      required:
        - developerMessage
        - errorCode
        - userMessage
      type: object
      properties:
        errorCode:
          maxLength: 6
          pattern: "^[a-zA-Z]+$\\d+$"
          type: string
          example: "6"
        developerMessage:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: Coding Error
        userMessage:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: Error al validar dispositvo
        moreInfo:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: ""
        version:
          maxLength: 256
          pattern: "^[a-zA-Z\\s]*$"
          type: string
          example: 1.0.0
        status:
          maxLength: 15
          type: number
          example: 409
  responses:
    BadRequest:
      description: 400 Bad Request. The request information it's not correct.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: 401 Unauthorized.You're not authorized to perform this operation.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: 403 Forbidden. You don't have the right permissions to execute this operation.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 404 Not Found. The server cannot find the requested resource.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: 500 Internal Server Error. An error has occurred.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'
    GatewayError:
      description: 502 Bad Gateway. The service unable to get a valid response.
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/Error'